### ISSUE TITLE
Downloading PNG assets not working on iconscout

### ISSUE THREAD

**Issue by yvan99** [kyutefox/Iconify#10]
I'm trying to download png and animated assets on iconscout but It keeps loading .  heres the console error im getting
<img width="958" alt="error iconify" src="https://github.com/kyutefox/Iconify/assets/23630154/91372e77-06d2-49c8-9506-d28b1db87601">

**Comment by razoo-choudhary** [comment]
@yvan99 animated assets and PNG are not supported for now, the only supported format is SVG, We are working on the update to support other formats.

**Comment by yvan99** [comment]
Okay, Thanks @razoo-choudhary . I liked this btw!
