### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by TenUchikawa** [kyutefox/Iconify#11]
Context
https://iconscout.com/lottie/social-media-influencer-4920128

```
   $('meta[data-n-head="ssr"][property="og:product_id"]').each(function(){
        product_id      = $(this).attr("content");
        let propEditor  = $(document).find("#pdpColorEditor-" + product_id).html();
        if(propEditor.length > 0)
        {
            setTimeout(function(){
                downloadIcon(propEditor, product_id);
                clickedButtonElement.html("Download");
```

![image](https://github.com/kyutefox/Iconify/assets/63717580/f8d830d6-7d76-476f-993e-3063777d4f5d)

**Comment by razoo-choudhary** [comment]
@TenUchikawa hello, the icon you are trying to download is an animated icon from IconScout, which is currently not supported by our extension we are working on new update that will support animated icons plus other icon libraries too.

**Comment by TenUchikawa** [comment]
I see that there were other Issues. Sorry. I will close it.
