### ISSUE TITLE
I installed and does not work. It sends me to the buy premium page

### ISSUE THREAD

**Issue by burlibu** [kyutefox/Iconify#13]

**Comment by razoo-choudhary** [comment]
You must login after installing, if on firefox make sure to give all the permissions.

**Comment by burlibu** [comment]
Now works thanks!

Il giorno mar 29 ago 2023 alle 12:43 Raju Choudhary <
***@***.***> ha scritto:

**Comment by razoo-choudhary** [comment]
@burlibu sure to star the project if this helps ♥️
