### ISSUE TITLE
Iconify does not work anymore in fierefox.

### ISSUE THREAD

**Issue by Santiagoc57** [kyutefox/Iconify#15]
Until a few days ago the extension was working correctly in firefox without any problem, started september it started to fail; it doesn't allow to download icons specifically from Flaticon, when I press download SVG (crown button) a warning appears in the lower right corner asking me to login, however I'm already logged in. I have tried it in incognito mode and other computers and I get the same error.

I would be very grateful if you could check it, thank you in advance.

**Comment by razoo-choudhary** [comment]
@Santiagoc57 Hi, If you are facing Please Login Issue even after being logged in, open the respective icon site in your case flaticon and let it load fully then simply press CTRL + R and reload the site. You are good to go again.
