### ISSUE TITLE
How to download directly from the homepage?

### ISSUE THREAD

**Issue by EuphoriaJP** [kyutefox/Iconify#16]
Thanks for your efforts for this great extension! 

I know that I can click the svg button to download the svg at the inner page (which means that I need to click the icon from the homepage to the inner page, as shown in Fig 1).

Could you please tell me how to download the svg directly from the homepage? (as shown in Fig 2)

Any information would be greatly appreciated!

![image](https://github.com/kyutefox/Iconify/assets/66820714/78ee6cbe-c0d0-4aab-8fa2-f8bbae8396a8)
![image](https://github.com/kyutefox/Iconify/assets/66820714/c394c7cb-7aaa-455c-937d-59664d055810)

**Comment by razoo-choudhary** [comment]
@EuphoriaJP Thank you for your suggestion, Currently we dont have that option. We will soon add this feature to the extension.
