### ISSUE TITLE
Doesn't work with iconscout

### ISSUE THREAD

**Issue by Tanya2196** [kyutefox/Iconify#18]
I log in via chrome and try to download but it gives me an error

**Comment by razoo-choudhary** [comment]
@Tanya2196 Login in to IconScout and then try hard reload by pressing (CTRL + R) or (Command + R) and it will work as normal.

**Comment by Tanya2196** [comment]
![IMG_0465](https://github.com/kyutefox/Iconify/assets/153959397/df6526f9-3ead-4781-a9a5-9ebef7319b57)

**Comment by razoo-choudhary** [comment]
@Tanya2196 3d icons are not available.
