### ISSUE TITLE
on icons8 does work well

### ISSUE THREAD

**Issue by mhr5246** [kyutefox/Iconify#20]
i think icons 8  update some part of website and this plugin doesn't work any more
please solve this

**Comment by razoo-choudhary** [comment]
@mhr5246 We will look into it.

**Comment by razoo-choudhary** [comment]
@mhr5246 Thank you for bringing the issue to our attention. We have addressed the problem and implemented the necessary updates to resolve it. 😊

**Comment by mhr5246** [comment]
@razoo-choudhary 
that's a great work. thank you.
let's connect on LinkedIn.😊
