### ISSUE TITLE
Chrome Iconify Download Error Issue

### ISSUE THREAD

**Issue by tuffscripts** [kyutefox/Iconify#21]
Followed Everything you mentioned in Docs and i get this error when i try to download any 3d icon.

![image](https://github.com/kyutefox/Iconify/assets/156289155/6d87d324-ff0d-4c55-a4f4-d019a62cfc79)

**Comment by tuffscripts** [comment]
![image](https://github.com/kyutefox/Iconify/assets/156289155/dac79337-2a40-48fc-ad2a-636364c78961)
After reviewing your jsscript , some files are not supported yet i guess !
![image](https://github.com/kyutefox/Iconify/assets/156289155/6eedd0ac-c1fa-4792-b067-96fc8a5b05e8)

Take this as a reference for these types of files, if you will add support for it:
https://iconscout.com/3d-illustration/speedometer-5334042

**Comment by razoo-choudhary** [comment]
@tuffscripts we currently dont support 3d icons.

**Comment by tuffscripts** [comment]
Any update on this , when you will add support for 3d icons ?

**Comment by razoo-choudhary** [comment]
@tuffscripts We will update you soon.
