### ISSUE TITLE
IconScout Not Working 

### ISSUE THREAD

**Issue by sagardhadke** [kyutefox/Iconify#23]
When click on Download Button redirecting on Plan and pricing page, I use Hard Reload the page but still same issue

**Comment by MrJukeman** [comment]
@sagardhadke Please update to the latest version 1.0.4 and clear your cache and then try downloading.

**Comment by sagardhadke** [comment]
I Just Download your extension, But still same issue

**Comment by MrJukeman** [comment]
@sagardhadke We tested and is working absolutely fine, What browser are you using ?

**Comment by sagardhadke** [comment]
Google Chrome

**Comment by sagardhadke** [comment]
See This screen recording :- https://www.mediafire.com/file/cn0qq716cu1r7ag/Extensions+-+Google+Chrome+2024-03-20+11-00-50.mp4/file

**Comment by MrJukeman** [comment]
@sagardhadke Thank you for the video, Currently 3D icons are not supported for downloads. From IconScout you can download SVG and Lottie Annimated Icons only. For that you Have to click on the icon and a popup comes with a button Named Download and that button helps you to download the icon for free.

**Comment by sagardhadke** [comment]
Lottie Json animation also not work

**Comment by sagardhadke** [comment]
See this Screen Recording Not working IconScout Any Service**
Video Link :- https://www.mediafire.com/file/k0g7pkmxdmse6gh/IconScout+Not+Working+·+Issue+#23+·+kyutefox_Iconify+-+Google+Chrome+2024-03-21+23-07-37.mp4/file

**Comment by mhr5246** [comment]
> I Just Download your extension, But still same issue

hi did you sign in to the website?

**Comment by sagardhadke** [comment]
yes

**Comment by MrJukeman** [comment]
@sagardhadke 

This is how I download the icon.

https://www.mediafire.com/file/24r5i7au9w0tizr/Screen+Recording+2024-03-23+at+3.09.45 PM.mov/file

**Comment by sagardhadke** [comment]
Still same, i reinstall the extension

**Comment by sagardhadke** [comment]
I install the extension in Firefox it's working properly

**Comment by sagardhadke** [comment]
Please update the extension for 3D icon also
