### ISSUE TITLE
When will 3D format files be supported for download?

### ISSUE THREAD

**Issue by veker007** [Kyutefox/Iconify#24]
When will 3D format files be supported for download?

**Comment by MrJukeman** [comment]
@veker007 The 3D Icon Support Has Been Added in v1.0.5

**Comment by veker007** [comment]
thanks

**Comment by veker007** [comment]
Amazing, thank you. Is there a plan to support the download of 3D format files such as OBJ?

**Comment by MrJukeman** [comment]
@veker007 Yes we have that in our bucket list.

**Comment by mhr5246** [comment]
please add streamlinehq.com

**Comment by MrJukeman** [comment]
@mhr5246 Thank you for the suggestion. We will look into it.

**Comment by veker007** [comment]
https://www.flaticon.com  animated icons Unable to download

**Comment by aiataya** [comment]
Thank you!! This is crazy, I'm tired of subscribtions and your tool is working!
