### ISSUE TITLE
Logo in your README

### ISSUE THREAD

**Issue by Zemerik** [Kyutefox/Iconify#26]
To enhance the look of your README, lets add the project's official Logo / favicon and some fantasy icons to attract Users and appear more catchy!

**Comment by MrJukeman** [comment]
@Zemerik Thank you for your suggestion, Why not be a contributor create a pull request with your idea of README and make that our official README

**Comment by Zemerik** [comment]
Sure, I can do that! Can you just provide me with the Logo / Favicon of your website?

**Comment by MrJukeman** [comment]
@Zemerik this is the official website of the organization:
https://kyutefox.com/
you will get everything here
For project specific icons you can get from the src/icons folder

**Comment by Zemerik** [comment]
Thanks @MrJukeman . I will soon open a PR to fix this issue 👍

**Comment by MrJukeman** [comment]
@Zemerik We will be waiting for the magic

**Comment by Zemerik** [comment]
https://github.com/Zemerik/Iconify - I am using this fork to resolve this issue, feel free to suggest any improvements or fixes as I navigate my way through the Repository.

**Comment by MrJukeman** [comment]
@Zemerik Sure ❤️
