### ISSUE TITLE
iconscout download files 0B

### ISSUE THREAD

**Issue by veker007** [Kyutefox/Iconify#34]
![WechatIMG343](https://github.com/user-attachments/assets/b0f22a90-e117-488f-8f13-d063ecd04562)
iconscout download files 0B
https://iconscout.com/icon-pack/e-commerce-1032

**Comment by MrJukeman** [comment]
@veker007 We will soon be updating our extension.

**Comment by MrJukeman** [comment]
@veker007 @champolot The 0 Byte issue has been fixed as minor update. Rolling the major update soon thank you for your love and support

**Comment by champolot** [comment]
thank you so much to for keeping this update. I highly appreciate all of this efforts ❤️❤️❤️. Cheers!
