### ISSUE TITLE
IconScout Not Working

### ISSUE THREAD

**Issue by sagardhadke** [Kyutefox/Iconify#37]
When click on Download Button redirecting on Plan and pricing page, I use Hard Reload the page but still same issue

**Comment by champolot** [comment]
I suggest you to remove you cache.

**Comment by sagardhadke** [comment]
I Try but still not working any premium assets

**Comment by champolot** [comment]
Try to reinstall the extension
Another 1 thing you could do is. Select an asset then reload it

Reload and reinstall worked to me

**Comment by sagardhadke** [comment]
I just ReInstall the extension, and hard reload the page it's now working but sometimes show a blank white page so please try to fix this issue
