### ISSUE TITLE
not working on flaticon on chrome browser

### ISSUE THREAD

**Issue by mohammed-el-amine-kichah** [Kyutefox/Iconify#39]

**Comment by ngohuyha19** [comment]
i still download icons on flaticon normally, u can try to clear cookies, then logged in and download icons again.

**Comment by champolot** [comment]
Refresh again the browser if it doesn't work

**Comment by keyboardWitch** [comment]
I met the same problem

**Comment by MrJukeman** [comment]
@mohammed-el-amine-kichah @ngohuyha19 @champolot @keyboardWitch Sorry for the delay response. Thank you for bringing the issue up. We will start the fix as soon as this comment is posted. We will come with a stable solution within 2 days.

**Comment by marcossantosfl** [comment]
not working in iconsscout anymore

**Comment by ngohuyha19** [comment]
> solu

We are always waiting for you to give an update.

**Comment by ngohuyha19** [comment]
> @mohammed-el-amine-kichah @ngohuyha19 @champolot @keyboardWitch Sorry for the delay response. Thank you for bringing the issue up. We will start the fix as soon as this comment is posted. We will come with a stable solution within 2 days.

We are always waiting for you to give an update.

**Comment by MrJukeman** [comment]
@marcossantosfl it should work on iconscout, we will still figure out the issue and solve it
