### ISSUE TITLE
another style problem in font awesome

### ISSUE THREAD

**Issue by themonoor** [Kyutefox/Iconify#43]
in font awesome, we cant download another style
like this:
https://fontawesome.com/icons/face-awesome?f=classic&s=regular
or this:
https://fontawesome.com/icons/face-awesome?f=sharp-duotone&s=solid

**Comment by ngohuyha19** [comment]
i still download those icons by using Iconify, please try reseting your browser and download them again

**Comment by MrJukeman** [comment]
@ngohuyha19 thank you for your support
