### ISSUE TITLE
Iconscout not working

### ISSUE THREAD

**Issue by husanui** [Kyutefox/Iconify#44]
![image](https://github.com/user-attachments/assets/9d00111e-e73b-4d9b-8f15-fdd430c66a2e)
not working iconscout

**Comment by champolot** [comment]
Maybe you could try other browser to view the file? I guess your browser doesnt support the viewing of svg? "shrug"

**Comment by MrJukeman** [comment]
@husanui @champolot New update is on the way

**Comment by champolot** [comment]
Thank you so much for keeping this updated! godbless! cheers!

**Comment by MrJukeman** [comment]
@husanui @champolot The latest version has been updated to include the fix. Thank you for your patience.
