### ISSUE TITLE
Icons8 fully not working and iconscout lottie-animation download problem

### ISSUE THREAD

**Issue by itsrakibroni** [Kyutefox/Iconify#46]
![Screenshot_1](https://github.com/user-attachments/assets/f2fbf0b5-cf45-466e-b52f-af801e9950cc)
loading but not work.

**Comment by champolot** [comment]
For iconscout If it loads forever, reload the page. If nothing works. Delete cache then reload the page.

**Comment by MrJukeman** [comment]
@itsrakibroni @champolot The latest version has been updated to include the fix. Thank you for your patience.
