### ISSUE TITLE
Currently encountering an error message when downloading an svg frile from iconscout 

### ISSUE THREAD

**Issue by champolot** [Kyutefox/Iconify#47]
![Screenshot 2024-10-25 191408](https://github.com/user-attachments/assets/b6e8a61c-ac45-4794-aef2-5af2ffff0133)

**Comment by champolot** [comment]
I assume that Icon scout updated their security feature. Specially before , you are able to download the file without using the extension by just using right click then download.

**Comment by duongthanhthai** [comment]
same issues :(

**Comment by veker007** [comment]
The downloads are all svg changed from html

**Comment by champolot** [comment]
What browser are you guys using?? I'm using chrome

**Comment by veker007** [comment]
chrome
![WX20241030-092030](https://github.com/user-attachments/assets/06620f55-a615-44b2-885e-e6055383ac3c)

**Comment by MrJukeman** [comment]
@champolot we have found the fix and the new update is on the way 😀

**Comment by champolot** [comment]
Thank you so much for this update!

**Comment by duongthanhthai** [comment]
> @champolot we have found the fix and the new update is on the way 😀

Thanks, we are waiting.
How do donate for your team? I can donate with paypal.

**Comment by MrJukeman** [comment]
@duongthanhthai  @champolot @veker007 The latest version has been updated to include the fix. Thank you for your patience.

**Comment by MrJukeman** [comment]
> > @champolot we have found the fix and the new update is on the way 😀
> 
> Thanks, we are waiting. How do donate for your team? I can donate with paypal.

You can donate through our website :)
