### ISSUE TITLE
May I ask when a new version will be available for use?

### ISSUE THREAD

**Issue by veker007** [Kyutefox/Iconify#48]
May I ask when a new version will be available for use?

https://iconscout.com/  svg don't download

**Comment by marcossantosfl** [comment]
yes, it stopped.

Possibly they already know and fixed it

**Comment by MrJukeman** [comment]
@veker007 @marcossantosfl  our bug has been fixed by the site and we have found another way to work on it, the update is on the way 😀

**Comment by anuragggg** [comment]
May i ask, when will be the new update released @MrJukeman

**Comment by ngohuyha19** [comment]
> May i ask, when will be the new update released @MrJukeman

I think it doesn't have a particular time for the new update. All we need to do now is wait.

**Comment by MrJukeman** [comment]
@ngohuyha19 @anuragggg @marcossantosfl @veker007 The latest version has been updated to include the fix. Thank you for your patience.

**Comment by MrJukeman** [comment]
@ngohuyha19 The update was delayed due to three consecutive updates pushed by Iconscout, which continuously addressed issues with the tunnel we were using.
