### ISSUE TITLE
Flaticon IP Ban

### ISSUE THREAD

**Issue by tnguyen2018** [Kyutefox/Iconify#50]
Does anyone get banned from flaticon for using this extension? I can't sign in with my home IP address but switching to mobile data worked. Usage wise, I only download maybe 1 or 2 svg per 2-3 months so not sure why my IP is flagged. This might be a permanent ban since it been a few weeks. Not hoping for a solution, just putting here as a precaution.

**Comment by champolot** [comment]
Maybe its just on your end. Maybe you could clear your cache and try re logging again.

**Comment by tnguyen2018** [comment]
Clearing cache doesn't work. But the behavior is definitely in line with an IP ban. I can still circumvent the ban by using the phone's network to establish the connection then sign-in. Just want to add here for info only and awareness, since it seems like these sites do check (sometimes...).

**Comment by MrJukeman** [comment]
@tnguyen2018 The IP Ban usually occurs from the ISP, You can ask your ISP to fix the internet issue.
