### ISSUE TITLE
Error when trying to download animated icon or static icon in iconscout.com 

### ISSUE THREAD

**Issue by iChwn** [kyutefox/Iconify#8]
I'm facing this error when trying to download some icons in iconscout.com
![image](https://github.com/kyutefox/Iconify/assets/29217999/8db0a722-6477-412f-8256-926fb580d7c1)
![image](https://github.com/kyutefox/Iconify/assets/29217999/94f006b2-f604-482b-a429-a1c18c688f01)

Any solutions to fix this?

**Comment by razoo-choudhary** [comment]
@iChwn Animated Icons are currently not possible to download, we are working on its update.

**Comment by Joseph-Nathan** [comment]
thanks for your great work ,

**Comment by alliialpha** [comment]
When I click on anyiconscout 3D icon to download, only the icon rotates and nothing downloads!!!!

**Comment by razoo-choudhary** [comment]
@alliialpha The absence of an SVG format for the 3D icons is causing errors or leading to icon loops. We are actively working on an update to address this issue promptly.

**Comment by razoo-choudhary** [comment]
@iChwn If you are still experiencing difficulties when downloading the regular SVG icon, you can try performing a hard reload to resolve the issue. This fix will be included in our upcoming updates.

Note : This issue is only for IconScout.
